### ISSUE TITLE
What does it take to use this for an F7?

### ISSUE THREAD

**Issue by wucke13** [stm32-rs/stm32-eth#12]
I'm interested in using this on an F7, for example an 767. What does it take to make that work?

**Comment by dtjones190** [comment]
WIP and documentation is not updated, but I have my fork running on a Nucleo-F767ZI dev board.
https://github.com/dtjones190/stm32-eth
You may need to change the hard coded clock setting in lib.rs line 98 to match your configuration.

**Comment by thalesfragoso** [comment]
We now have support for the F7 family on master :tada:
