### ISSUE TITLE
Please publish version 0.2.0 on crates.io

### ISSUE THREAD

**Issue by dutchmartin** [stm32-rs/stm32-eth#29]
While trying to use this crate, I copied the following from the readme:
`stm32-eth = { version = "0.2.0", features = ["stm32f767"]}`
To my surprise, this does not work since that version is [not published on crates.io](https://lib.rs/crates/stm32-eth)
So can someone publish the new version?

In the meantime, I will use:
 `stm32-eth = { git = "https://github.com/stm32-rs/stm32-eth.git", branch = "master", features = ["stm32f767"]}`

Please let me know if there is something I can help with.

**Comment by astro** [comment]
Done, thanks for the reminder.
