### ISSUE TITLE
error when compiling STM32 on Arduino ID

### ISSUE THREAD

**Issue by bryamfajardo** [stm32-rs/stm32-eth#36]
When I compile the programming given by the manufacturer of the Gravity sensor: Analog EMG SEN024, I get the following programming error:
 
Arduino:1.8.17 Hourly Build 2021/09/06 02:33 (Windows 10), Tarjeta:"Generic STM32F103C series, STM32F103C8 (20k RAM. 64k Flash), STM32duino bootloader, 72Mhz (Normal), Smallest (default)"

C:\Users\Bryam\Downloads\prueba_defecto_2\prueba_defecto\prueba_defecto.ino: In function 'void setup()':

prueba_defecto:38:56: error: invalid conversion from 'int' to 'SAMPLE_FREQUENCY' [-fpermissive]

     myFilter.init(sampleRate, humFreq, true, true, true);

                                                        ^

In file included from C:\Users\Bryam\Downloads\prueba_defecto_2\prueba_defecto\prueba_defecto.ino:9:0:

C:\Users\Bryam\OneDrive\Documentos\Arduino\libraries\EMGFilters/EMGFilters.h:57:10: error:   initializing argument 1 of 'void EMGFilters::init(SAMPLE_FREQUENCY, NOTCH_FREQUENCY, bool, bool, bool)' [-fpermissive]

     void init(SAMPLE_FREQUENCY sampleFreq,

          ^

prueba_defecto:38:56: error: invalid conversion from 'int' to 'NOTCH_FREQUENCY' [-fpermissive]

     myFilter.init(sampleRate, humFreq, true, true, true);

                                                        ^

In file included from C:\Users\Bryam\Downloads\prueba_defecto_2\prueba_defecto\prueba_defecto.ino:9:0:

C:\Users\Bryam\OneDrive\Documentos\Arduino\libraries\EMGFilters/EMGFilters.h:57:10: error:   initializing argument 2 of 'void EMGFilters::init(SAMPLE_FREQUENCY, NOTCH_FREQUENCY, bool, bool, bool)' [-fpermissive]

     void init(SAMPLE_FREQUENCY sampleFreq,

          ^

Se encontraron varias bibliotecas para "Wire.h"

Usado: C:\Users\Bryam\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2021.5.31\libraries\Wire

 No usado: C:\Users\Bryam\AppData\Local\Arduino15\packages\stm32duino\hardware\STM32F1\2021.5.31\libraries\WireSlave

exit status 1

invalid conversion from 'int' to 'SAMPLE_FREQUENCY' [-fpermissive]

**Comment by thalesfragoso** [comment]
Sorry, this isn't related to this repository. I hope you can find the resolution but there isn't nothing we can do about it here.
