### ISSUE TITLE
v0.3 on crates.io

### ISSUE THREAD

**Issue by sveinrou** [stm32-rs/stm32-eth#47]
Hey, v0.3 doesn't seem to be published on crates.io

https://crates.io/crates/stm32-eth

**Comment by astro** [comment]
@thalesfragoso I have invited you to the package owners on crates.io.

**Comment by thalesfragoso** [comment]
@astro Sorry, the invitation got lost in my inbox and it actually expired (I didn't even know that was a thing), could you please send it again ?

**Comment by datdenkikniet** [comment]
Fixed! v0.3.0 has been released on [crates.io](https://crates.io/crates/stm32-eth/0.3.0)
