### ISSUE TITLE
Bump stm32f7xx-hal v0.7.0

### ISSUE THREAD

**Issue by sveinrou** [stm32-rs/stm32-eth#51]
There's a new version of stm32f7xx-hal as of Jun 15, would be nice to get it in here

**Comment by datdenkikniet** [comment]
FYI, we're already using this in the `master` branch. I'll try to figure out who to poke to get a new release out sometime soon that also includes this version.

**Comment by datdenkikniet** [comment]
Astro has given me ownership rights, now. A new release will be published tomorrow!

**Comment by datdenkikniet** [comment]
Fixed! v0.3.0 has been released on [crates.io](https://crates.io/crates/stm32-eth/0.3.0)
